feat: realize getting data for favorite page
Dekim12/iTechArt-StudentsLab pull request #10
Opened 2019-03-07 09:35 UTC by Dekim12

2019-03-07 13:27 UTC, AntonPashkowskiy requested changes

2019-03-07 13:27 UTC, AntonPashkowskiy commented on src/js/components/BeerLabel/BeerLabel.js
> +    const isFavorite = addToLocalStorage(id);
isOperationCompleted лучше. потому что не понятно как addToLocalStorage может возвращать характеристику пива.

2019-03-07 13:27 UTC, AntonPashkowskiy commented on src/js/components/BeerLabel/BeerLabel.js
> +    if (isFavorite) {
this.setState({ isChecked: isFavorite }) =) пора на выходные

2019-03-07 13:27 UTC, AntonPashkowskiy commented on src/js/components/BeerPage/BeerPage.js
> +    if (isFavorite) {
то же самое =)

2019-03-07 13:27 UTC, AntonPashkowskiy commented on src/js/components/BeerPage/BeerPage.js
> +    if (isEmpty) {
тернарный оператор =) тебе же не доплачивают за лишние строчки кода

2019-03-07 13:27 UTC, AntonPashkowskiy commented on src/js/components/FavoritesPage/FavoritesPage.js
> +    if (
опять 25! использование true \ false по условию if всегда должно настораживать - а не херню ли я пишу)

2019-03-07 13:27 UTC, AntonPashkowskiy commented on src/js/redux/containers/FavoritePageContainer.js
> +  const favoriteBeers = JSON.parse(localStorage.getItem('favoriteList'));
appLogic/logic.js - почему получение их не там? знание о localStorage должны быть в одном месте. что бы легко можно было на что-то другое заменить.

2019-03-11 09:45 UTC, Dekim12 commented on src/js/components/BeerPage/BeerPage.js
> +    if (isEmpty) {
здесь никак не получится тернарный оператор вставить, так как возвращать должно три разных результата при проаерке двух условий

2019-03-12 07:15 UTC, AntonPashkowskiy approved these changes

2019-03-12 07:15 UTC, merged