Task 4: the beerPage and the beerLabel
Dekim12/iTechArt-StudentsLab pull request #7
Opened 2019-02-28 13:26 UTC by Dekim12

2019-02-28 14:27 UTC, AntonPashkowskiy requested changes

2019-02-28 14:27 UTC, AntonPashkowskiy commented on src/js/appLogic/utils.js
> +export const generateKey = () => {
Найди лучше какую нибудь библиотеку вроде uuid. :) Таким обычно никто вручную не занимается.

2019-02-28 14:27 UTC, AntonPashkowskiy commented on src/js/components/BeerLabel/BeerLabel.js
> +          OPEN
То что оно написано большими буквами всего лишь стилизация. OPEN -> Open, text-transform: uppercase -> CSS

2019-02-28 14:27 UTC, AntonPashkowskiy commented on src/js/components/BeerLabel/BeerLabel.js
> +          makeChanges={() => console.log('btn works')}
Такая функция будет создаваться каждый раз при рендеринге компонента. А следовательно будут разные ссылки, и компонент будет перерендериваться тогда, когда ничего не поменялось. Для stateless компонентов по моему есть набор функций позволяющих это сделать в 'react'.

2019-02-28 14:27 UTC, AntonPashkowskiy commented on src/js/components/BeerPage/BeerPage.js
> +  if (!beersData || match.params.id > 234 || match.params.id < 1) {
Магические числа недопустимы. Это даже не константа. Если тебе API вернёт больше пива чем 234, то у тебя все после них перестанут отображаться.

2019-02-28 14:27 UTC, AntonPashkowskiy commented on src/js/components/BeerPage/BeerPage.js
> +          makeChanges={() => console.log('btn works')}
в итоговом коде не должно быть console.log ни на что кроме ошибок, и то лучше так не делать

2019-02-28 14:27 UTC, AntonPashkowskiy commented on src/js/components/FavoritesPage/FavoritesPage.js
> +  <section className='page favorites-page'>this is a Favorites page</section>
Когда решил что-то поменять в своей жизни :)

2019-02-28 14:27 UTC, AntonPashkowskiy commented on src/js/components/Properties/Properties.js
> +          <span className='prop-value'>{floorValue(abv)}</span>
копипаста. можно было бы сделать объект ключ\значение и пройтись по ключам отрендерив таким образом пары - tooltip\abberviation

2019-02-28 14:27 UTC, AntonPashkowskiy commented on src/js/components/Properties/Properties.js
> +const Properties = ({ abv, ibu, ebc }) => {
я понимаю что в данных они названы так, но простому читателю этого кода такие имена переменных ни о чём не говорят

2019-02-28 14:27 UTC, AntonPashkowskiy commented on src/js/components/Properties/Properties.js
> +          <span className='prop-value'>{floorValue(abv)}</span>
ещё лучше конечно было бы придумать как смапить модель данных так, что бы при добавлении аббревиатур на сервере они рендерились тут

2019-02-28 14:27 UTC, AntonPashkowskiy commented on src/js/redux/reducers/pagesState.js
> +      return { ...state, beerPageData: action.payload };
Зачем тебе распаковывать тут кусок state который пришёл? За него ведь отвечает только этот reducer а больше тут пока ничего нет, кроме beerPageData.

2019-02-28 14:27 UTC, AntonPashkowskiy commented on src/js/components/BeerPage/BeerPage.js
> +  const beer = selectionNecessaryData(beersData, match.params.id);
Почему это не может сделать контейнер?

2019-02-28 14:34 UTC, Dekim12 commented on src/js/components/BeerPage/BeerPage.js
> +  if (!beersData || match.params.id > 234 || match.params.id < 1) {
Про магическое понял. API больше не вернет там всего 234. это защита, если пользователь введет сам больше 234

2019-02-28 14:38 UTC, Dekim12 commented on src/js/components/BeerPage/BeerPage.js
> +          makeChanges={() => console.log('btn works')}
это я поставил временно. там будет функция для добавления в "любимое"

2019-02-28 14:39 UTC, Dekim12 commented on src/js/components/FavoritesPage/FavoritesPage.js
> +  <section className='page favorites-page'>this is a Favorites page</section>
нее.. начать жизнь с чистого листа)

2019-02-28 14:53 UTC, Dekim12 commented on src/js/components/BeerPage/BeerPage.js
> +  const beer = selectionNecessaryData(beersData, match.params.id);
Контейнер ничего не знает об id. Он только передает данные, из которые потом нужно выбрать нужный элемент исходя из id

2019-02-28 14:57 UTC, Dekim12 commented on src/js/components/BeerLabel/BeerLabel.js
> +          makeChanges={() => console.log('btn works')}
просто у меня Button это компонент. И на событие onClick  он вызовет функцию которая придет в пропс. Я решил выделить кнопку как компонент, что бы в разных местах можно было использовать. Правильно ли это или такое лучше не отделять?

2019-02-28 14:59 UTC, Dekim12 commented on src/js/components/BeerPage/BeerPage.js
> +  if (!beersData || match.params.id > 234 || match.params.id < 1) {
Без этой проверки приложение упадет. А потом при выпалнении данного условия я дабавлю компонент который говорит что такого элемента нет.

2019-02-28 15:00 UTC, Dekim12 commented on src/js/components/Properties/Properties.js
> +          <span className='prop-value'>{floorValue(abv)}</span>
немного не понял "при добавлении аббревиатур на сервере они рендерились тут"

2019-02-28 15:27 UTC, Dekim12 commented on src/js/components/BeerPage/BeerPage.js
> +  const beer = selectionNecessaryData(beersData, match.params.id);
id получает как url пораметр через react router

2019-03-01 10:04 UTC, AntonPashkowskiy approved these changes

2019-03-01 10:04 UTC, merged